-- Группа
CREATE TABLE группа
(
	id_группа integer GENERATED BY DEFAULT AS IDENTITY, 
	специальность character varying(10) NOT NULL, 
	отделение character varying(15) NOT NULL, 
	количество_студентов integer NOT NULL,
	PRIMARY KEY (id_группа)
);
-- Вставка значений в группу
INSERT INTO группа
(специальность, отделение, количество_студентов) VALUES
	('2.09.03.03', 'Очное', 15), 
	('2.09.03.04', 'Очное', 13), 
	('2.14.03.02', 'Заочное', 8),
	('2.09.04.07', 'Очное', 22);


-- Преподаватель
CREATE TABLE преподаватель
(
	id_преподаватель integer GENERATED BY DEFAULT AS IDENTITY, 
	фамилия text NOT NULL,  		
	имя text NOT NULL,  		
	отчество text NOT NULL, 		
	телефон text NOT NULL,  		
	стаж smallint NOT NULL, 	
	PRIMARY KEY (id_преподаватель)
);
	
-- Вставка в таблицу преподаватель
INSERT INTO преподаватель
(фамилия, имя, отчество, телефон, стаж) VALUES 
	('Иванов', 'Иван', 'Иванович', '78005553535', 5), 
	('Семенов', 'Семен', 'Семенович', '79088099088', 2),
	('Сергеев', 'Сергей', 'Сергеевич', '79998887776', 10);
	
-- Нагрузка
CREATE TABLE нагрузка
(
	id_нагрузка integer GENERATED BY DEFAULT AS IDENTITY,
	id_преподаватель integer NOT NULL,
    id_группа integer NOT NULL,
    количество_часов smallint NOT NULL,				
    предмет text NOT NULL,						
    тип_занятия character varying(8) NOT NULL,	
    оплата real NOT NULL,
	PRIMARY KEY (id_нагрузка),
	CONSTRAINT преподаватель_exists FOREIGN KEY (id_преподаватель)
        REFERENCES преподаватель (id_преподаватель)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT группа_exists FOREIGN KEY (id_группа)
        REFERENCES группа (id_группа)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);	

-- Вставка в таблицу нагрузка
INSERT INTO нагрузка
(id_преподаватель, id_группа, количество_часов, предмет, тип_занятия, оплата) VALUES 
	(1, 2, 9, 'Компьютерная графика', 'Лекция', 500),
	(3, 2, 18, 'Базы данных', 'Практика', 250),
	(2, 3, 15, 'Теоретическая физика', 'Лекция', 500),
	(2, 3, 25, 'Высшая математика', 'Лекция', 700);