--
-- PostgreSQL database dump
--

-- Dumped from database version 13.1
-- Dumped by pg_dump version 13.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: lombard; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE lombard WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'Russian_Russia.1251';

CREATE TABLE public."Категория товара" (
    "ID_Категория" integer NOT NULL,
    "Название категории" character varying(30) NOT NULL
);


ALTER TABLE public."Категория товара" OWNER TO postgres;

--
-- Name: Категория товара_ID_Категория_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Категория товара" ALTER COLUMN "ID_Категория" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Категория товара_ID_Категория_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Клиент; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Клиент" (
    "ID_Клиент" integer NOT NULL,
    "Фамилия клиента" character varying(30) NOT NULL,
    "Имя клиента" character varying(30) NOT NULL,
    "Отчество клиента" character varying(30),
    "Телефон клиента" character varying(15) NOT NULL
);


ALTER TABLE public."Клиент" OWNER TO postgres;

--
-- Name: Клиент_ID_Клиент_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Клиент" ALTER COLUMN "ID_Клиент" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Клиент_ID_Клиент_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Место хранения; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Место хранения" (
    "ID_Место" integer NOT NULL,
    "Название" character varying(30) NOT NULL,
    "Площадь" double precision NOT NULL
);


ALTER TABLE public."Место хранения" OWNER TO postgres;

--
-- Name: Место хранения_ID_Место_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Место хранения" ALTER COLUMN "ID_Место" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Место хранения_ID_Место_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Производитель; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Производитель" (
    "ID_Производитель" integer NOT NULL,
    "Название производителя" character varying(30) NOT NULL
);


ALTER TABLE public."Производитель" OWNER TO postgres;

--
-- Name: Производитель_ID_Производитель_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Производитель" ALTER COLUMN "ID_Производитель" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Производитель_ID_Производитель_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Сделка; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Сделка" (
    "ID_Сделка" integer NOT NULL,
    "ID_Клиент" integer NOT NULL,
    "ID_Товар" integer NOT NULL,
    "ID_Сотрудник" integer NOT NULL,
    "Дата изготовления" date NOT NULL,
    "Дата оформления" date NOT NULL,
    "Срок хранения" date NOT NULL,
    "Сумма реализации" double precision NOT NULL,
    "Сумма, выданная под залог" double precision NOT NULL,
    "Доход" double precision NOT NULL,
    "ID_Состояние" integer NOT NULL,
    "ID_Место" integer NOT NULL
);


ALTER TABLE public."Сделка" OWNER TO postgres;

--
-- Name: Сделка_ID_Сделка_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Сделка" ALTER COLUMN "ID_Сделка" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Сделка_ID_Сделка_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Состояние товара; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Состояние товара" (
    "ID_Состояние" integer NOT NULL,
    "Название состояния" character varying(40) NOT NULL
);


ALTER TABLE public."Состояние товара" OWNER TO postgres;

--
-- Name: Состояние товара_ID_Состояние_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Состояние товара" ALTER COLUMN "ID_Состояние" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Состояние товара_ID_Состояние_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Сотрудник; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Сотрудник" (
    "ID_Сотрудник" integer NOT NULL,
    "Имя сотрудника" character varying(30) NOT NULL,
    "Фамилия сотрудника" character varying(30) NOT NULL,
    "Отчество сотрудника" character varying(30),
    "Телефон сотрудника" character varying(15) NOT NULL,
    "Зарплата сотрудника" double precision NOT NULL
);


ALTER TABLE public."Сотрудник" OWNER TO postgres;

--
-- Name: Сотрудник_ID_Сотрудник_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Сотрудник" ALTER COLUMN "ID_Сотрудник" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Сотрудник_ID_Сотрудник_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Товар; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Товар" (
    "ID_Товар" integer NOT NULL,
    "Наименование товара" character varying(50) NOT NULL,
    "Оценочная стоимость" double precision NOT NULL,
    "ID_Производитель" integer NOT NULL,
    "ID_Категория" integer NOT NULL
);


ALTER TABLE public."Товар" OWNER TO postgres;

--
-- Name: Товар_Код товара_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Товар" ALTER COLUMN "ID_Товар" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Товар_Код товара_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: Категория товара; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Категория товара" VALUES (1, 'Пылесосы');
INSERT INTO public."Категория товара" VALUES (2, 'Ювелирные изделия');
INSERT INTO public."Категория товара" VALUES (3, 'Видеокарты');


--
-- Data for Name: Клиент; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Клиент" VALUES (1, 'Пупкин', 'Василий', 'Павлович', '+79246123999');
INSERT INTO public."Клиент" VALUES (2, 'Иванов', 'Иван', 'Алексеевич', '+79246123345');
INSERT INTO public."Клиент" VALUES (3, 'Алексеев', 'Алексей', 'Иванович', '+79246424924');


--
-- Data for Name: Место хранения; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Место хранения" VALUES (1, 'Витрина', 15);
INSERT INTO public."Место хранения" VALUES (2, 'Основной склад', 120);
INSERT INTO public."Место хранения" VALUES (3, 'Подсобка', 40);


--
-- Data for Name: Производитель; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Производитель" VALUES (1, 'ASUS');
INSERT INTO public."Производитель" VALUES (2, 'Sunlight');
INSERT INTO public."Производитель" VALUES (3, 'Samsung');


--
-- Data for Name: Сделка; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Сделка" VALUES (2, 1, 1, 2, '2019-03-26', '2021-01-15', '2021-01-29', 0, 7000, 0, 1, 1);
INSERT INTO public."Сделка" VALUES (3, 2, 3, 1, '2020-05-08', '2021-01-18', '2021-01-23', 0, 6500, 0, 3, 1);
INSERT INTO public."Сделка" VALUES (1, 3, 2, 1, '2020-07-15', '2021-01-06', '2021-01-12', 30000, 22000, 8000, 4, 3);


--
-- Data for Name: Состояние товара; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Состояние товара" VALUES (1, 'В залоге');
INSERT INTO public."Состояние товара" VALUES (2, 'Просрочено хранение');
INSERT INTO public."Состояние товара" VALUES (3, 'Выкуплен');
INSERT INTO public."Состояние товара" VALUES (4, 'Реализован по истечению времени');


--
-- Data for Name: Сотрудник; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Сотрудник" VALUES (1, 'Михаил', 'Зубенко', 'Петрович', '+79096999999', 25650);
INSERT INTO public."Сотрудник" VALUES (2, 'Михаил', 'Терентьев', 'Павлович', '+79096999888', 32550);
INSERT INTO public."Сотрудник" VALUES (3, 'Никита', 'Михалков', 'Сергеевич', '+79096595858', 43500);


--
-- Data for Name: Товар; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Товар" VALUES (1, ' GeForce GTX 1060 DUAL', 15000, 1, 3);
INSERT INTO public."Товар" VALUES (2, 'Jet 75 pet', 35000, 3, 1);
INSERT INTO public."Товар" VALUES (3, 'Золотая цепь', 12000, 2, 2);


--
-- Name: Категория товара_ID_Категория_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Категория товара_ID_Категория_seq"', 3, true);


--
-- Name: Клиент_ID_Клиент_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Клиент_ID_Клиент_seq"', 3, true);


--
-- Name: Место хранения_ID_Место_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Место хранения_ID_Место_seq"', 3, true);


--
-- Name: Производитель_ID_Производитель_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Производитель_ID_Производитель_seq"', 3, true);


--
-- Name: Сделка_ID_Сделка_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Сделка_ID_Сделка_seq"', 3, true);


--
-- Name: Состояние товара_ID_Состояние_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Состояние товара_ID_Состояние_seq"', 7, true);


--
-- Name: Сотрудник_ID_Сотрудник_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Сотрудник_ID_Сотрудник_seq"', 3, true);


--
-- Name: Товар_Код товара_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Товар_Код товара_seq"', 3, true);


--
-- Name: Категория товара Категория товара_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Категория товара"
    ADD CONSTRAINT "Категория товара_pkey" PRIMARY KEY ("ID_Категория");


--
-- Name: Клиент Клиент_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Клиент"
    ADD CONSTRAINT "Клиент_pkey" PRIMARY KEY ("ID_Клиент");


--
-- Name: Место хранения Место хранения_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Место хранения"
    ADD CONSTRAINT "Место хранения_pkey" PRIMARY KEY ("ID_Место");


--
-- Name: Производитель Производитель_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Производитель"
    ADD CONSTRAINT "Производитель_pkey" PRIMARY KEY ("ID_Производитель");


--
-- Name: Сделка Сделка_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Сделка"
    ADD CONSTRAINT "Сделка_pkey" PRIMARY KEY ("ID_Сделка");


--
-- Name: Состояние товара Состояние товара_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Состояние товара"
    ADD CONSTRAINT "Состояние товара_pkey" PRIMARY KEY ("ID_Состояние");


--
-- Name: Сотрудник Сотрудник_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Сотрудник"
    ADD CONSTRAINT "Сотрудник_pkey" PRIMARY KEY ("ID_Сотрудник");


--
-- Name: Товар Товар_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Товар"
    ADD CONSTRAINT "Товар_pkey" PRIMARY KEY ("ID_Товар");


--
-- Name: Сделка Сделка_ID_Клиент_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Сделка"
    ADD CONSTRAINT "Сделка_ID_Клиент_fkey" FOREIGN KEY ("ID_Клиент") REFERENCES public."Клиент"("ID_Клиент");


--
-- Name: Сделка Сделка_ID_Место_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Сделка"
    ADD CONSTRAINT "Сделка_ID_Место_fkey" FOREIGN KEY ("ID_Место") REFERENCES public."Место хранения"("ID_Место");


--
-- Name: Сделка Сделка_ID_Состояние_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Сделка"
    ADD CONSTRAINT "Сделка_ID_Состояние_fkey" FOREIGN KEY ("ID_Состояние") REFERENCES public."Состояние товара"("ID_Состояние");


--
-- Name: Сделка Сделка_ID_Сотрудник_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Сделка"
    ADD CONSTRAINT "Сделка_ID_Сотрудник_fkey" FOREIGN KEY ("ID_Сотрудник") REFERENCES public."Сотрудник"("ID_Сотрудник");


--
-- Name: Сделка Сделка_ID_Товар_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Сделка"
    ADD CONSTRAINT "Сделка_ID_Товар_fkey" FOREIGN KEY ("ID_Товар") REFERENCES public."Товар"("ID_Товар");


--
-- Name: Товар Товар_ID_Категория_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Товар"
    ADD CONSTRAINT "Товар_ID_Категория_fkey" FOREIGN KEY ("ID_Категория") REFERENCES public."Категория товара"("ID_Категория");


--
-- Name: Товар Товар_ID_Производитель_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Товар"
    ADD CONSTRAINT "Товар_ID_Производитель_fkey" FOREIGN KEY ("ID_Производитель") REFERENCES public."Производитель"("ID_Производитель");


--
-- PostgreSQL database dump complete
--

